name: Generate Trim JSONs
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Python script
        run: python generate_trim_models.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/copperequipment/models/item/
          git diff-index --quiet HEAD || (git commit -m "Generate trim JSON files" --allow-empty && git push)
